services:
  coverart:
    image: ${COVERART_IMAGE:-epochaudio/coverart:3.1.8}
    container_name: ${COVERART_CONTAINER_NAME:-coverart-app}
    init: true
    pull_policy: missing
    environment:
      NODE_ENV: production
      ROON_PERSIST_PATH: /app/config.json
    network_mode: "host"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - type: bind
        source: ./images
        target: /app/images
      - type: bind
        source: ./config/local.json
        target: /app/config/local.json
        read_only: true
      - type: bind
        source: ./config.json
        target: /app/config.json
